/**
 * @file dynamics.h
 * @brief Handles the packet generation, routing, and traffic dynamics simulation across the multilayer network.
 */

 // Global variable definitions
extern int** ABC;          // Adjacency matrix of the coupled multilayer network
extern int* D_ABC;         // Degree array of the coupled network
extern int** B_ABC;        // Adjacency list of the coupled network
extern int** path_num_ABC; // Number of shortest paths in the coupled network
extern int*** path_ABC;    // Shortest paths in the coupled network
extern int distance_ABC[TOTAL_NODES][TOTAL_NODES];

extern const int C_ave;
extern double* C_ABC;

extern double r_packet_sta;   // Starting packet generation rate
extern double r_packet_end;   // Ending packet generation rate
extern double r_packet_inter; // Packet generation rate interval

double r_packet;  // Current packet generation rate
int r_integer;    // Integer part of r_packet
double r_decimal; // Decimal part of r_packet

const int times_length = 5000;
const int break_time = 3000;

extern int circuit;
extern double* eita;

int trans[TOTAL_NODES];
int Q[TOTAL_NODES];
int mess_length;

extern double p;
extern int current_timestep;
extern string configType;
extern string network_type;

/**
 * @brief Structure representing a packet/message node in the network.
 */
struct MessNode
{
    int location;      // Current node location
    int destination;   // Target destination node
    int born_timestep; // Timestep when the packet was generated
    MessNode* link;    // Pointer to the next packet in the queue
};
typedef MessNode* MessNodePtr;

/**
 * @brief Class managing the queue of packets in the simulation.
 */
class Mess
{
public:
    Mess();
    ~Mess();
    void add(int location, int destination, int born_timestep);
    void del(MessNodePtr last, MessNodePtr now);
    void del_head();
    void update_tail(MessNodePtr node) {
        tail = node;
    }
    void debug_info() const {
        cout << "Mess object: head=" << head << ", tail=" << tail << endl;
    }
    MessNodePtr get_head();
    MessNodePtr get_tail();
private:
    MessNodePtr head;
    MessNodePtr tail;
};

// Constructor
Mess::Mess()
{
    head = nullptr;
    tail = nullptr;
}

// Destructor
Mess::~Mess()
{
    MessNodePtr ptr, temp;
    for (ptr = head; ptr != NULL;)
    {
        temp = ptr;
        ptr = ptr->link;
        delete temp;
    }
}

/**
 * @brief Adds a new packet to the queue.
 */
void Mess::add(int location, int destination, int born_timestep)
{
    if (head == NULL) { // Empty queue
        head = new MessNode;
        head->destination = destination;
        head->location = location;
        head->born_timestep = born_timestep;
        head->link = nullptr;  // Ensure initialization to nullptr
        tail = head;
        return;
    }

    // Non-empty queue
    MessNodePtr temp = new MessNode;
    temp->location = location;
    temp->destination = destination;
    temp->born_timestep = born_timestep;
    temp->link = nullptr;
    tail->link = temp;
    tail = temp;
}

/**
 * @brief Deletes a packet from the middle or end of the queue.
 */
void Mess::del(MessNodePtr last, MessNodePtr now)
{
    MessNodePtr temp = now;
    last->link = now->link;
    if (now == tail)
        tail = last;
    delete temp;
}

/**
 * @brief Deletes the packet at the head of the queue.
 */
void Mess::del_head()
{
    MessNodePtr temp = head;
    head = head->link;
    if (head == NULL) // Queue becomes empty
        tail = NULL;
    delete temp;
}

MessNodePtr Mess::get_head()
{
    return head;
}

MessNodePtr Mess::get_tail()
{
    return tail;
}

extern std::mt19937 global_rng;

inline double random_double() {
    static std::uniform_real_distribution<> dis(0.0, 1.0);
    return dis(global_rng);
}

inline int random_int(int min, int max) {
    std::uniform_int_distribution<> dis(min, max);
    return dis(global_rng);
}

/**
 * @brief Generates new packets at the current timestep based on the generation rate.
 * @param mess_que Reference to the global packet queue.
 * @param mess_length Reference to the total number of packets currently in the system.
 * @param timestep The current simulation timestep.
 */
void multi_mess_born_multi_layer(Mess& mess_que, int& mess_length, int timestep) {
    int i, j;
    int destination;
    int amount; // Number of packets generated by the current node at this timestep

    std::uniform_real_distribution<double> dist(0.0, 1.0);
    std::uniform_int_distribution<int> node_dist(0, TOTAL_NODES - 1);

    current_timestep = timestep; // Update current timestep

    for (i = 0; i < TOTAL_NODES; i++) // Iterate through all nodes
    {
        // Calculate the number of packets generated at this timestep
        double random_dec = dist(global_rng);

        if (r_decimal > 0 && random_dec < r_decimal)
            amount = r_integer + 1;
        else
            amount = r_integer;

        // Assign destinations and add to queue
        for (j = 0; j < amount; j++)
        {
            // Determine the source layer
            int source_layer = i / N;

            // Decide if the transmission is cross-layer
            double rand_val = dist(global_rng);

            if (rand_val < p) {
                // Inter-layer traffic: select a destination in a different layer
                do {
                    destination = node_dist(global_rng);
                } while (destination / N == source_layer || destination == i);
            }
            else {
                // Intra-layer traffic: select a destination within the same layer
                int layer_start = source_layer * N;
                do {
                    destination = layer_start + (node_dist(global_rng) % N);
                } while (destination == i);
            }

            mess_que.add(i, destination, timestep); // Add packet to queue
            ++Q[i];        // Increment queue length at source node
            mess_length++; // Increment total packet count
        }
    }
}

/**
 * @brief Processes packet routing and delivery for a single timestep.
 * @param mess_que Reference to the global packet queue.
 * @param mess_length Reference to the total number of packets currently in the system.
 * @param timestep The current simulation timestep.
 */
void multi_mess_deliver_multi_layer(Mess& mess_que, int& mess_length, int timestep) {

    MessNodePtr ptr;       // Pointer to current packet being processed
    MessNodePtr q = NULL;  // Pointer to previous packet 

    // Iterate through all packets in the queue
    for (ptr = mess_que.get_head(); ptr != NULL; )
    {
        int location = ptr->location;
        int destination = ptr->destination;
        int born_timestep = ptr->born_timestep;

        // Determine layers for source and destination
        int source_layer = location / N;
        int dest_layer = destination / N;

        // Determine routing strategy based on source and destination layers
        int next;
        if (source_layer == dest_layer) {
            // Same layer: use single-layer routing
            int layer_index = source_layer;
            int src_local = location % N;
            int dest_local = destination % N;

            if (path_num_single[layer_index][src_local][dest_local] <= 0) {
                MessNodePtr temp = ptr;
                ptr = ptr->link;
                if (q == nullptr) {
                    mess_que.del_head();
                }
                else {
                    mess_que.del(q, temp);
                }
                --mess_length;
                --Q[location];
                continue;
            }

            // Select shortest path randomly if multiple exist
            int sel_num = path_num_single[layer_index][src_local][dest_local];
            int random = std::uniform_int_distribution<>(0, sel_num - 1)(global_rng);
            next = path_single[layer_index][src_local][dest_local][random];

            // Convert local node index to global index
            next = source_layer * N + next;
        }
        else {
            // Different layers: use global coupled-network routing
            if (path_num_ABC[location][destination] <= 0 || path_ABC[location][destination] == nullptr) {
                MessNodePtr temp = ptr;
                ptr = ptr->link;
                if (q == nullptr) {
                    mess_que.del_head();
                }
                else {
                    mess_que.del(q, temp);
                }
                --mess_length;
                --Q[location];
                continue;
            }

            int sel_num = path_num_ABC[location][destination];
            int random = std::uniform_int_distribution<>(0, sel_num - 1)(global_rng);
            next = path_ABC[location][destination][random];
        }

        // Check node processing capacity (integer part)
        if (trans[location] == floor(C_ABC[location]))
        {
            // Process fractional capacity probabilistically
            if (static_cast<double>(rand()) / static_cast<double>(RAND_MAX) >= double(C_ABC[location] - floor(C_ABC[location]))) {
                q = ptr;
                ptr = ptr->link;
                continue; // Skip transmission for this timestep
            }
        }
        // Exceeded processing capacity
        else if (trans[location] > floor(C_ABC[location]))
        {
            q = ptr;
            ptr = ptr->link;
            continue; // Skip
        }

        // Validate next hop
        if (next < 0 || next >= TOTAL_NODES) {
            q = ptr;
            ptr = ptr->link;
            continue;
        }

        // Update queue and transmission count
        --Q[location];     // Decrease queue length at current node
        trans[location]++; // Increment transmission count        

        // Check if destination is reached
        if (next == destination)
        {
            MessNodePtr temp = ptr;
            ptr = ptr->link;

            // Remove packet from queue
            if (q == NULL)
                mess_que.del_head();
            else {
                mess_que.del(q, temp);
            }
            --mess_length;
        }
        else
        {
            // Forward to intermediate node
            ptr->location = next;
            ++Q[next];
            q = ptr;
            ptr = ptr->link;
        }
    }
}

/**
 * @brief Main function executing the traffic dynamics simulation over varying generation rates.
 */
void multi_dyn_spr()
{
    ofstream out_file("result(MultiLayer_"+ network_type + "_" + configType + "_k=" + to_string(LAYER_COUNT) + ")" + to_string(p) + ".txt");
    out_file << "r_packet\teita\n";

    int mess_length; // Current total number of packets

    cout << "Starting packet transmission simulation..." << endl;

    // Outer loop: iterate through different packet generation rates
    for (r_packet = r_packet_sta; r_packet < r_packet_end + r_packet_inter; r_packet = r_packet + r_packet_inter)
    {
        r_integer = static_cast<int>(floor(r_packet));
        r_decimal = r_packet - r_integer;

        double* packet_num = new double[times_length - break_time];

        for (int i = 0; i < circuit + 1; i++)
        {
            eita[i] = 0;
        }

        // Middle loop: Repeat simulation 'circuit' times and average
        for (int cir_count = 0; cir_count < circuit; cir_count++)
        {
            // Reset state
            mess_length = 0;
            Mess mess_que;

            for (int i = 0; i < TOTAL_NODES; i++) {
                Q[i] = 0;
                trans[i] = 0;
            }

            for (int time_temp = 0; time_temp < times_length - break_time; time_temp++)
                packet_num[time_temp] = 0;

            // Inner Loop 1: Warm-up phase (data not recorded)
            for (int timestep = 0; timestep < break_time; timestep++)
            {
                for (int i = 0; i < TOTAL_NODES; i++)
                    trans[i] = 0;

                multi_mess_born_multi_layer(mess_que, mess_length, timestep);
                multi_mess_deliver_multi_layer(mess_que, mess_length, timestep);
            }

            // Inner Loop 2: Statistical phase (record message volume)
            for (int timestep = break_time; timestep < times_length; timestep++)
            {
                for (int i = 0; i < TOTAL_NODES; i++)
                    trans[i] = 0;

                multi_mess_born_multi_layer(mess_que, mess_length, timestep);
                multi_mess_deliver_multi_layer(mess_que, mess_length, timestep);

                // Record total packet count at current timestep
                packet_num[timestep - break_time] = mess_length;
            }

            // Calculate order parameter (rate of change in packet volume)
            for (int temp1 = 0; temp1 < (times_length - break_time) / 2; temp1++)
            {
                eita[cir_count] += double(packet_num[temp1 + (times_length - break_time) / 2] - packet_num[temp1])
                    / double((times_length - break_time) / 2);
            }
            eita[cir_count] /= double((times_length - break_time) / 2);
            eita[cir_count] = eita[cir_count] / (r_packet * N);
        }

        delete[] packet_num;

        // Average across all circuit runs
        for (int cir_count = 0; cir_count < circuit; cir_count++)
        {
            eita[circuit] += eita[cir_count];
        }
        eita[circuit] /= double(circuit);

        // Output result
        out_file << r_packet << "\t" << eita[circuit] << endl;
    }

    cout << "Simulation completed!" << endl;
    out_file.close();
}